# Assignment 2 

   ## Author : Tathagato Roy 

## Roll Number : 2019111020

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import math
import random


## Q1

### Subpart A

$$\text{Single Value Decomposition is more generalizable to Matrices than Eigen Value }$$
$$\text{Decomposition as Single Value Decomposition } $$
$$\text{can applied for both square and rectangular matrices,whereas Eigen Value Decomposition }$$
$$\text{is only applicable to Square Matrices,} $$
$$\text{even then it is not applicable to all Square Matrices,just symmetric ones.} $$

### Subpart B

$$ \text{We have a matrix M :} $$
$$\begin{bmatrix}
4 & 8\\
11 & 7\\
14 & -2\end{bmatrix}
$$

$$\text{We want to compute U, }\Sigma \text{ and V such that :}$$

$$ M = U\Sigma V^T $$

$$\text{Where U is 3}\times 3 \text{ unitary matrix, } \Sigma \text{ is 3}\times 2 \text{ rectangular Diagonal Matrix and V is a 2}\times 2 \text{ Unitary Matrix}$$

$$ C = M^TM = \begin{bmatrix} 333 & 81 \\ 81 & 117 \end{bmatrix} $$

$$ det(C - \lambda  I) = \begin{bmatrix} {333 - \lambda} & 81  \\ 81 & {117 - \lambda}  \end{bmatrix} $$

$$ \implies det(C - \lambda I) = (333 - \lambda)(117 - \lambda) - 81^2 $$
$$ \implies det(C- \lambda I) = \lambda^2 - 450\lambda + 32400 $$
$$ \implies det(C - \lambda I) = \lambda^2  - 360\lambda - 90\lambda + 90*360 $$
$$ \implies det(C - \lambda I) = (\lambda - 360)(\lambda - 90) $$
$$\text{ By setting } det(C - \lambda I) = 0 \text{ We get } \lambda = 90,360 $$


$$\text{The Eigen Values of C is therefore } \lambda_1 = 360,\lambda_2 = 90 $$

$$ \text{The singular Values are given by  }\sigma_1 = 6\sqrt{10} \text{  } \sigma_2 = 3\sqrt{10}$$

$$ \text{Hence we get } \Sigma = \begin{bmatrix} {6\sqrt{10}} & 0 \\ 0 & 3\sqrt{10}  \\ 0 & 0  \end{bmatrix} $$

$$\text{The columns of the Matrix V are the orthonormal eigenvectors of the Matrix } C = M^TM $$

$$ \text{The eigenvectors } v_1,v_2 \text{of the Matrix C can be computed by solving the set of Following equations} $$
$$ C v_1 = \sigma_1^2 v_1  \implies (C - \sigma_1^2 I)v_1 = 0 $$
$$ C v_2 = \sigma_2^2 v_2  \implies (C - \sigma_2^2 I)v_2 = 0 $$

$$ \text{which is equivalent to computing the null space of the matrices } D_i = (C - \sigma_i^2 I) \text{ for } i = 1,2 $$





$$ \text{ while this can done by solving the set of linear equations ,}$$
$$ \text{but it is extremely tedious.We can compute the eigen vector more easily by using a numpy function } $$

In [2]:
M = np.array([[4,8],[11,7],[14,-2]])
print(M)
print(M.shape)

[[ 4  8]
 [11  7]
 [14 -2]]
(3, 2)


In [3]:
M_T = M.T
print(M_T)
print(M_T.shape)

[[ 4 11 14]
 [ 8  7 -2]]
(2, 3)


In [9]:
C = np.matmul(M_T,M)
print(C)
print(C.shape)

[[333  81]
 [ 81 117]]
(2, 2)


In [13]:
w , v = np.linalg.eig(C)
print("EigenValues : ")
print(w)
print("EigenVectors : ")
print(v)

EigenValues : 
[360.  90.]
EigenVectors : 
[[ 0.9486833  -0.31622777]
 [ 0.31622777  0.9486833 ]]


In [21]:
e1 = v[:,0]
e2 = v[:,1]
print(e1)
print(e2)
print(M)
s1 = np.sqrt(w[0])
s2 = np.sqrt(w[1])
print(s1)
print(s2)
ans1 = np.matmul(M,e1)/s1
ans2 = np.matmul(M,e2)/s2
print(ans1)
print(ans2)


[0.9486833  0.31622777]
[-0.31622777  0.9486833 ]
[[ 4  8]
 [11  7]
 [14 -2]]
18.973665961010276
9.486832980505138
[0.33333333 0.66666667 0.66666667]
[ 0.66666667  0.33333333 -0.66666667]


$$ \text{The normalized Eigenvectors are : }$$


$$ v_1 = \begin{bmatrix} 0.948 \\ 0.316  \end{bmatrix} $$


$$ v_2 = \begin{bmatrix} -0.316 \\ 0.948 \end{bmatrix} $$


$$ \text{ Note that this vectors are not unique,given there are 3 other choice of combination(by selectively multiplying } $$
$$ v_1,v_2 \text{ with - 1. Also note that } v_1,v_2 \text{are ordered according to decreasing order of the modulus }$$
$$\text{their respective Eigenvalue.}$$

$$ V = \begin{bmatrix} v_1 & v_2  \end{bmatrix} $$
$$ \implies V = \begin{bmatrix} 0.948 & -0.316 \\ 0.316 & 0.948  \end{bmatrix} $$ 

$$\text{Now we want to compute U which a 3X3 Matrix. We know columns of U forms of Orthonormal }$$
$$\text{Basis of the Space Ax.} $$
$$ \text{The singular Values of A is } \sqrt 90 \text{ and } \sqrt 360 $$
$$\text{ hence the rank of A is 2 as there are two singular Values.}$$
$$\text{Therefore the rank of Ax is also 2.The first two columns of U is therefore given by : } $$
$$ u_1 = \frac{Av_1}{\sigma_1} $$
$$ u_2 = \frac{Av_2}{\sigma_2} $$

$$ u_1 = \frac{1}{\sigma_1}\begin{bmatrix}4 & 8\\11 & 7\\14 & -2\end{bmatrix}\begin{bmatrix} 0.948 \\ 0.316 \end{bmatrix} $$
$$ \implies u_1 = \begin{bmatrix} 1/3 \\ 2/3 \\ 2/3 \end{bmatrix} $$
$$ u_2 = \frac{1}{\sigma_1}\begin{bmatrix}4 & 8\\11 & 7\\14 & -2\end{bmatrix}\begin{bmatrix}  0.316 \\ 0.948  \end{bmatrix} $$
$$ \implies u_2 = \begin{bmatrix} 2/3 \\ 1/3 \\ -2/3 \end{bmatrix} $$


$$ \text{We need to compute } u_3 \text{ such that } u_1^T u_3 = 0 \text{ and } u_2^T u_3 = 0 \text{ that is } u_3 \text{ is normal to space spanned by } u_1 \text{ and } u_2 $$

$$ \text{One such example of } u_3 \text{ is } \begin{bmatrix} 2/3 \\ -2/3 \\ 1/3 \end{bmatrix} $$

$$ U = \begin{bmatrix} 1/3 & 2/3 & 2/3 \\ 2/3 & 1/3 & -2/3 \\ 2/3 & -2/3 & 1/3 \end{bmatrix} $$


$$ \text{ Hence  } M = \begin{bmatrix} 1/3 & 2/3 & 2/3 \\ 2/3 & 1/3 & -2/3 \\ 2/3 & -2/3 & 1/3 \end{bmatrix}  \begin{bmatrix} {3\sqrt{10}} & 0 \\ 0 & 6\sqrt{10}  \\ 0 & 0  \end{bmatrix} \begin{bmatrix} 0.948 & -0.316 \\ 0.316 & 0.948  \end{bmatrix}^T $$

Sanity Check :

In [25]:
U = np.array([[1/3,2/3,2/3],[2/3,1/3,-2/3],[2/3,-2/3,1/3]])
S = np.array([[np.sqrt(360),0],[0,np.sqrt(90)],[0,0]])
V = np.array([[0.948,-0.316],[0.316,0.948]])
M_1 = np.matmul(U,np.matmul(S,V.T))
print(M_1)
print("Difference")
print(M - M_1)

[[ 3.99711896  7.99423792]
 [10.99207715  6.99495818]
 [13.98991637 -1.99855948]]
Difference
[[ 0.00288104  0.00576208]
 [ 0.00792285  0.00504182]
 [ 0.01008363 -0.00144052]]


## Q2

### Subpart A

$$ \text{Assumption : The Decomposition is a SVD Decomposition and hence D is a diagonal Matrix} $$
$$ \text{Option B is correct as one Single Value being larger than the other suggest one is the principle component} $$
$$\text{If both the diagonal values are equal,then there is no way to find the principle component.}$$

$$ \text{Option C is also Correct.As all the points in X lie in a straight line, therefore the columns of X }$$
$$ \text{which is NX2 Matrix are not linearly Independent and therefore its rank is 1,and as such the number of }$$
$$ \text{nonzero singular value in D is also 1.Hence D is not full rank}$$

### Subpart B

$$\text{It is False.It is not neccessary PCA preserves Useful Information for MultiClass Classification,}$$
$$\text{only just that it maximizes the variance} $$

### Q3

### Subpart A

In Bayesian Statistic The Prior Probability indicates the probability of Random Event / Uncertain Quantity before any data is collected/sampled. 
It is a expression of our belief about this Random Event / Uncertain Quantity before any evidence is taken into account.

The Posterior Probability is the conditional probability of a Random Event / Uncertain Quantity given we have now seen the Evidence/Data X.

$$ \text{Bayes Theorem :}$$
$$ P({\theta}|{X}) = \frac{P({X}|{\theta})P(\theta)}{P(X)} $$

$$ \text{Where : }$$
$$ P({\theta}|{X}) \text{ is the posterior Probability} $$
$$ P({X}|{\theta}) \text{is the Likelyhood of seeing X given the parameter } \theta $$
$$ P(\theta) \text{ is the prior probability of } \theta \text{ or our belief of quantity } \theta $$
$$ P(X) \text{ is the probability of seeing the evidence/Data X} $$

### Subpart B

$$\text{Let E be the event when someone have Sore throat and Headache}$$
$$\text{Let F be the event when someone have the flu}$$
$$ P(E) \text{is the probability of someone having the symptoms Sore Throat and Headache}$$
$$ P(F) \text{ is the probability of someone having the flu} $$
$$ P(E|F) \text{ is the probability someone having the headache and sore throat given they have the flu } $$
$$ P(F|E) \text{ is the probability someone having the flu given they have a headache and sore throat} $$
$$ \text{Given in the problem : } $$
$$ P(F) = 0.05 $$
$$ P(E) = 0.2 $$
$$ P(E|F) = 0.9 $$
$$ \text{We want to now compute P(F|E) ,i.e the probability of having the Flu given someone already has headache and sorethroat}$$
$$ \text{Using Bayes Theorem : } $$
$$ P(F|E) = \frac{P(E|F)*P(F)}{P(E} $$
$$ \implies P(F|E) = \frac{0.9*0.05}{0.2} $$
$$ \implies P(F|E) = \frac{9*5*10}{2*100*10} $$
$$ \implies P(F|E) = \frac{9}{40} $$
$$ \implies P(F|E) = 0.225 $$
$$ \text{Hence there is a 0.225 probability of someone having the Flu given they have headache and sore throat} $$